
from fastapi import APIRouter, UploadFile, File, HTTPException, Body
import os
import pdfplumber
import docx
import openai
from dotenv import load_dotenv
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import uuid
import json

router = APIRouter()

@router.post("/generate-scripts")
async def generate_scripts(course_json: dict = Body(...)):
    """
    Receives the JSON generated by the AI with the course and generates a detailed spoken script PDF for each lesson using the AI.
    Returns the names of the generated PDFs.
    """
    if not course_json.get("lessons"):
        raise HTTPException(status_code=400, detail="No lessons found in input JSON.")

    pdf_links = []
    for idx, lesson in enumerate(course_json["lessons"], 1):
        lesson_title = lesson.get("lesson", f"Lesson {idx}")
        topics = lesson.get("topics", [])
        # Prompt for the AI to generate the spoken script
        script_prompt = (
            f"You are an expert teacher. Generate a detailed spoken script for the lesson titled '{lesson_title}'. "
            f"Explain the following topics clearly and in a didactic way: {', '.join(topics)}. "
            "The script should be ready to be read in an educational video, with an introduction, development, and closing."
        )
        try:
            client = openai.OpenAI(api_key=openai.api_key)
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": script_prompt}]
            )
            script_text = response.choices[0].message.content
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Error generating script for lesson '{lesson_title}': {str(e)}")

        # Generate PDF
        pdf_filename = f"script_{uuid.uuid4().hex[:8]}_{idx}.pdf"
        pdf_path = os.path.join(UPLOAD_FOLDER, pdf_filename)
        c = canvas.Canvas(pdf_path, pagesize=letter)
        width, height = letter
        c.setFont("Helvetica-Bold", 14)
        c.drawString(40, height - 50, f"Lesson Script: {lesson_title}")
        c.setFont("Helvetica", 11)
        y = height - 80
        for line in script_text.split('\n'):
            if y < 60:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 11)
            c.drawString(40, y, line.strip())
            y -= 16
        c.save()
        pdf_links.append({"lesson": lesson_title, "pdf": pdf_filename})

    return {"scripts": pdf_links}



load_dotenv(os.path.join(os.path.dirname(__file__), '../../.env'))
router = APIRouter()

openai.api_key = os.getenv("OPENAI_API_KEY")

PROMPT = (
    "Given the following course syllabus, generate a JSON with: "
    "1. A course_title (generated by the AI), "
    "2. A course_description (brief, generated by the AI), "
    "3. lessons (list of lessons, each with a title and topics). "
    "Return the information in JSON format with the structure: "
    "{ 'course_title': '...', 'course_description': '...', 'lessons': [ { 'lesson': 'Lesson Title', 'topics': ['topic1', 'topic2', ...] } ] }. Syllabus: "
)

UPLOAD_FOLDER = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', 'uploads'))
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@router.get("/ping")
def ping():
    return {"message": "pong"}

@router.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    filename = file.filename
    if not (filename.endswith('.pdf') or filename.endswith('.docx')):
        raise HTTPException(status_code=400, detail="Unsupported format. Only PDF and DOCX are allowed.")
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    with open(filepath, "wb") as f:
        f.write(await file.read())
    extracted_text = None
    if filename.endswith('.pdf'):
        extracted_text = extract_text_from_pdf(filepath)
    elif filename.endswith('.docx'):
        extracted_text = extract_text_from_docx(filepath)

    # Send to OpenAI
    prompt = PROMPT + extracted_text
    try:
        client = openai.OpenAI(api_key=openai.api_key)
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        ia_result = response.choices[0].message.content
        # Try to parse the result as JSON
        try:
            course_json = json.loads(ia_result)
        except Exception:
            # If not valid JSON, return as text only
            return {"filename": filename, "ia_result": ia_result, "error": "AI result is not valid JSON."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error querying the AI: {str(e)}")

    # Generate scripts and PDFs automatically
    pdf_links = []
    if course_json.get("lessons"):
        for idx, lesson in enumerate(course_json["lessons"], 1):
            lesson_title = lesson.get("lesson", f"Lesson {idx}")
            topics = lesson.get("topics", [])
            script_prompt = (
                f"You are an expert teacher. Generate a highly detailed, specific, and engaging spoken script for the lesson titled '{lesson_title}'. "
                f"Explain the following topics thoroughly, with clear examples, analogies, and step-by-step explanations: {', '.join(topics)}. "
                "The script should be long enough to be read aloud for at least 15 minutes, and should include an introduction, a comprehensive development section, and a thoughtful closing. "
                "Make sure the script is continuous, not summarized, and covers all points in depth."
            )
            try:
                script_response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[{"role": "user", "content": script_prompt}]
                )
                script_text = script_response.choices[0].message.content
            except Exception as e:
                script_text = f"Error generating script: {str(e)}"

            # Generate PDF
            pdf_filename = f"script_{uuid.uuid4().hex[:8]}_{idx}.pdf"
            pdf_path = os.path.join(UPLOAD_FOLDER, pdf_filename)
            c = canvas.Canvas(pdf_path, pagesize=letter)
            width, height = letter
            c.setFont("Helvetica-Bold", 14)
            c.drawString(40, height - 50, f"Lesson Script: {lesson_title}")
            c.setFont("Helvetica", 11)
            y = height - 80
            # Split long lines for PDF rendering
            from reportlab.lib.utils import simpleSplit
            max_width = width - 80
            for line in script_text.split('\n'):
                wrapped_lines = simpleSplit(line.strip(), "Helvetica", 11, max_width)
                for wline in wrapped_lines:
                    if y < 60:
                        c.showPage()
                        y = height - 50
                        c.setFont("Helvetica", 11)
                    c.drawString(40, y, wline)
                    y -= 16
            c.save()
            pdf_links.append({"lesson": lesson_title, "pdf": pdf_filename})

    return {
        "filename": filename,
        "course_json": course_json,
        "scripts": pdf_links
    }

def extract_text_from_pdf(filepath):
    text = ""
    with pdfplumber.open(filepath) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text

def extract_text_from_docx(filepath):
    doc = docx.Document(filepath)
    return '\n'.join([p.text for p in doc.paragraphs])
