
from fastapi import APIRouter, UploadFile, File, HTTPException, Body
import os
import pdfplumber
import docx
import openai
import requests
import time
from dotenv import load_dotenv
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import uuid
import json

router = APIRouter()

load_dotenv(os.path.join(os.path.dirname(__file__), '../../.env'))
router = APIRouter()

openai.api_key = os.getenv("OPENAI_API_KEY")

PROMPT = (
    "Given the following course syllabus, generate a JSON with: "
    "1. A course_title (generated by the AI), "
    "2. A course_description (brief, generated by the AI), "
    "3. lessons (list of lessons, each with a title and topics). "
    "Return the information in JSON format with the structure: "
    "{ 'course_title': '...', 'course_description': '...', 'lessons': [ { 'lesson': 'Lesson Title', 'topics': ['topic1', 'topic2', ...] } ] }. Syllabus: "
)

UPLOAD_FOLDER = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', 'uploads'))
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@router.get("/ping")
def ping():
    return {"message": "pong"}

@router.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    filename = file.filename
    if not (filename.endswith('.pdf') or filename.endswith('.docx')):
        raise HTTPException(status_code=400, detail="Unsupported format. Only PDF and DOCX are allowed.")
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    with open(filepath, "wb") as f:
        f.write(await file.read())
    extracted_text = None
    if filename.endswith('.pdf'):
        extracted_text = extract_text_from_pdf(filepath)
    elif filename.endswith('.docx'):
        extracted_text = extract_text_from_docx(filepath)

    # Send to OpenAI
    prompt = PROMPT + extracted_text
    try:
        client = openai.OpenAI(api_key=openai.api_key)
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        ia_result = response.choices[0].message.content
        # Try to parse the result as JSON
        try:
            course_json = json.loads(ia_result)
        except Exception:
            # If not valid JSON, return as text only
            return {"filename": filename, "ia_result": ia_result, "error": "AI result is not valid JSON."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error querying the AI: {str(e)}")

    # Generate scripts and PDFs automatically
    pdf_links = []
    kahoot_quizzes = []
    if course_json.get("lessons"):
        for idx, lesson in enumerate(course_json["lessons"], 1):
            lesson_title = lesson.get("lesson", f"Lesson {idx}")
            topics = lesson.get("topics", [])
            script_prompt = (
                f"You are an expert teacher. Generate a highly detailed, specific, and engaging spoken script for the lesson titled '{lesson_title}'. "
                f"Explain the following topics thoroughly, with clear examples, analogies, and step-by-step explanations: {', '.join(topics)}. "
                "The script should be suitable to be read aloud in a video of up to 2 minutes (no more than half a page of text), and should include an introduction, development, and closing. "
                "Make sure the script is continuous, not summarized, and covers all points in depth, but keep the total length appropriate for a 2-minute presentation."
            )
            try:
                script_response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[{"role": "user", "content": script_prompt}]
                )
                script_text = script_response.choices[0].message.content
            except Exception as e:
                script_text = f"Error generating script: {str(e)}"

            # Generate PDF
            pdf_filename = f"script_{uuid.uuid4().hex[:8]}_{idx}.pdf"
            pdf_path = os.path.join(UPLOAD_FOLDER, pdf_filename)
            c = canvas.Canvas(pdf_path, pagesize=letter)
            width, height = letter
            c.setFont("Helvetica-Bold", 14)
            c.drawString(40, height - 50, f"Lesson Script: {lesson_title}")
            c.setFont("Helvetica", 11)
            y = height - 80
            # Split long lines for PDF rendering
            from reportlab.lib.utils import simpleSplit
            max_width = width - 80
            for line in script_text.split('\n'):
                wrapped_lines = simpleSplit(line.strip(), "Helvetica", 11, max_width)
                for wline in wrapped_lines:
                    if y < 60:
                        c.showPage()
                        y = height - 50
                        c.setFont("Helvetica", 11)
                    c.drawString(40, y, wline)
                    y -= 16
            c.save()
            if idx == 1:
                video = await generate_video_from_text(script_text)
                print("Video file name: "+video["filename"])
                print("Video path: "+video["path"])
                pdf_links.append({"lesson": lesson_title, "pdf": pdf_filename, "video": video["filename"]})
            else:
                pdf_links.append({"lesson": lesson_title, "pdf": pdf_filename})

            # Extract text from the generated PDF for quiz generation
            try:
                pdf_script_text = extract_text_from_pdf(pdf_path)
            except Exception as e:
                pdf_script_text = f"Error extracting text from PDF: {str(e)}"

            # Generate quiz based on the PDF content
            kahoot_quiz_json = []
            if pdf_script_text and topics:
                kahoot_prompt = (
                    f"You MUST generate exactly 1 challenging multiple choice question (with 4 options labeled A, B, C, D and one correct answer) for the following lesson script (extracted from the PDF). The question must require understanding, application, or analysis of the lesson content. Do not use general knowledge or information outside the script. Do not skip or refuse to generate the question for any reason. Return ONLY a valid JSON array with this structure: [{{'question': '...', 'options': ['A: ...', 'B: ...', 'C: ...', 'D: ...'], 'answer': 'A: ...'}}]. Do NOT use markdown or code blocks. Script: {pdf_script_text}"
                )
                try:
                    kahoot_response = client.chat.completions.create(
                        model="gpt-3.5-turbo",
                        messages=[{"role": "user", "content": kahoot_prompt}]
                    )
                    kahoot_quiz = kahoot_response.choices[0].message.content
                    # Clean up code blocks and markdown if present
                    if kahoot_quiz.strip().startswith("```"):
                        kahoot_quiz = kahoot_quiz.strip().lstrip("`json").lstrip("`").rstrip("`")
                        kahoot_quiz = kahoot_quiz.replace("```", "").replace("json", "").strip()
                    # Try to parse as JSON (force valid JSON)
                    import re
                    kahoot_quiz_json = []
                    quiz_str = kahoot_quiz
                    # Replace single quotes with double quotes for JSON compatibility
                    quiz_str = re.sub(r"'", '"', quiz_str)
                    # Remove trailing commas before closing brackets
                    quiz_str = re.sub(r',\s*([}\]])', r'\1', quiz_str)
                    # Try to extract JSON array with regex if parse fails
                    match = re.search(r'(\[.*\])', quiz_str, re.DOTALL)
                    if match:
                        quiz_str = match.group(1)
                    try:
                        kahoot_quiz_json = json.loads(quiz_str)
                        # Ensure it's a list of dicts with required keys
                        if not (isinstance(kahoot_quiz_json, list) and all(isinstance(q, dict) and 'question' in q and 'options' in q and 'answer' in q for q in kahoot_quiz_json)):
                            kahoot_quiz_json = []
                    except Exception:
                        kahoot_quiz_json = []
                except Exception as e:
                    kahoot_quiz_json = f"Error generating Kahoot quiz: {str(e)}"
            else:
                kahoot_quiz_json = "Quiz could not be generated due to missing script or topics."
            # Add 'Lesson X' label and 'Question X' to each question
            lesson_number = idx
            # Remove duplicate 'Lesson X:' if present
            lesson_title_clean = lesson_title
            expected_prefix = f"Lesson {lesson_number}: "
            if lesson_title.startswith(expected_prefix):
                lesson_title_clean = lesson_title[len(expected_prefix):]
            lesson_label = f"Lesson {lesson_number}: {lesson_title_clean}"
            formatted_quiz = []
            if isinstance(kahoot_quiz_json, list):
                for q_idx, q in enumerate(kahoot_quiz_json, 1):
                    question_label = f"Question {q_idx}"
                    formatted_quiz.append({
                        "question": f"{question_label}: {q.get('question', '')}",
                        "options": q.get('options', []),
                        "answer": q.get('answer', '')
                    })
            kahoot_quizzes.append({"lesson": lesson_label, "quiz": formatted_quiz})

    return {
        "filename": filename,
        "course_json": course_json,
        "scripts": pdf_links,
        "kahoot_quizzes": kahoot_quizzes
    }

HEYGEN_API_KEY = os.getenv("HEYGEN_API_KEY")
HEYGEN_API_URL = "https://api.heygen.com/v2/video/generate"
HEYGEN_STATUS_URL = "https://api.heygen.com/v1/video_status.get"


async def generate_video_from_text(script_text):
    headers = {"X-Api-Key": HEYGEN_API_KEY, "Content-Type": "application/json"}
    data = {
        "video_inputs": [{
            "character": {"type": "avatar", "avatar_id": "Georgia_sitting_office_front", "avatar_style": "normal"},
            "input_text": script_text,
            "voice": {"type": "text", "input_text": script_text, "voice_id": "79cb233e53e04419aa6f86db0ce8b192"}
        }],
        "dimension": {"width": 1280, "height": 720}
    }

    response = requests.post(HEYGEN_API_URL, headers=headers, json=data)
    if response.status_code != 200:
        try:
            error_detail = response.json()
        except Exception:
            error_detail = response.text
        raise HTTPException(status_code=response.status_code, detail=f"Error HeyGen: {error_detail}")

    res_json = response.json()
    video_id = res_json["data"]["video_id"]

    video_url = None
    max_retries = 60 # Wait 10-minute max for video generation (10s * 30)
    for _ in range(max_retries):
        time.sleep(10)
        status_res = requests.get(f"{HEYGEN_STATUS_URL}?video_id={video_id}", headers=headers)
        print(status_res.text)
        if status_res.status_code != 200:
            continue

        try:
            status_json = status_res.json()
        except Exception:
            continue


        status = status_json.get("data", {}).get("status")
        if status == "completed":
            video_url = status_json["data"]["video_url"]
            break
        elif status == "failed":
            raise HTTPException(status_code=500, detail="HeyGen video generation failed.")

    if not video_url:
        return {"message": "Video is taking longer than expected. ID: " + video_id}

    video_filename = f"video_{uuid.uuid4().hex[:8]}.mp4"
    video_path = os.path.join(UPLOAD_FOLDER, video_filename)

    video_data = requests.get(video_url).content
    with open(video_path, "wb") as f:
        f.write(video_data)

    return {
        "filename": video_filename,
        "path": video_path
    }


@router.post("/video1", tags=["Video Generation"])
async def generate_video(file: UploadFile = File(...)):
    """
    Use HeyGen to generate a video and store it in UPLOAD_FOLDER.
    """
    if not file.filename.endswith('.pdf'):
        raise HTTPException(status_code=400, detail="Only PDF files allowed.")

    temp_filename = f"temp_{uuid.uuid4().hex}_{file.filename}"
    temp_filepath = os.path.join(UPLOAD_FOLDER, temp_filename)

    with open(temp_filepath, "wb") as f:
        f.write(await file.read())

    try:
        script_text = extract_text_from_pdf(temp_filepath)
        if not script_text.strip():
            raise HTTPException(status_code=400, detail="The PDF is empty.")

        video = await generate_video_from_text(script_text)
        return {
            "message": "Video generated and saved successfully.",
            "video_filename": video["filename"],
            "video_path": video["path"]
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(temp_filepath):
            os.remove(temp_filepath)

def extract_text_from_pdf(filepath):
    text = ""
    with pdfplumber.open(filepath) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text

def extract_text_from_docx(filepath):
    doc = docx.Document(filepath)
    return '\n'.join([p.text for p in doc.paragraphs])
